# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="timewarrior-teamwork",
    version="0.1.0",
    description="TimeWarrior plugin for integration with Teamwork",
    python_requires="==3.*,>=3.8.0",
    author="Braden Mars",
    author_email="bradenmars@bradenmars.me",
    entry_points={"console_scripts": ["twtw = twtw.cli:cli"]},
    packages=["timewarrior-teamwork", "timewarrior-teamwork.twtw"],
    package_dir={"timewarrior-teamwork": ""},
    package_data={
        "timewarrior-teamwork": [
            "*.lock",
            "*.md",
            "*.toml",
            "timewarrior_teamwork.egg-info/*.txt",
        ]
    },
    install_requires=[
        "click==7.*,>=7.1.2",
        "dpath==2.*,>=2.0.1",
        "python-dateutil==2.*,>=2.8.1",
        "python-dotenv==0.*,>=0.13.0",
        "requests==2.*,>=2.23.0",
        "rich==2.*,>=2.2.6",
    ],
)
